### ISSUE TITLE
Unable to load libcryptonote.dll

### ISSUE THREAD

**Issue by WildeChild** [bonesoul/hypepool#11]
Running dotnet 2.0.5 on Debian 9.  I've downloaded and compiled the source with msbuild.  When I use dotnet to run the Cli, I receive the following after successfully seeing the banner:

```
Unhandled Exception: System.BadImageFormatException: Could not load file or assembly '/usr/src/hypepool/build/bin/Debug/netcoreapp2.0/libcryptonote.dll'. The module was expected to contain an assembly manifest.
   at System.Reflection.AssemblyName.nGetFileInformation(String s)
   at Hypepool.Core.Internals.Bootstrap.Bootstrapper.<>c.<HandlePackages>b__7_1(FileInfo file) in /usr/src/hypepool/src/Core/Hypepool.Core/Internals/Bootstrap/Bootstrapper.cs:line 56
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at Hypepool.Core.Internals.Bootstrap.Bootstrapper.HandlePackages() in /usr/src/hypepool/src/Core/Hypepool.Core/Internals/Bootstrap/Bootstrapper.cs:line 58
   at Hypepool.Core.Internals.Bootstrap.Bootstrapper.Run() in /usr/src/hypepool/src/Core/Hypepool.Core/Internals/Bootstrap/Bootstrapper.cs:line 32
   at Hypepool.Cli.Program.Main(String[] args) in /usr/src/hypepool/src/Core/Hypepool.Cli/Program.cs:line 18
Aborted
```

Any recommendations?  I feel like I must be missing something in the build phase.  I first tried grunt to build, but it wasn't straight forward how to get that working in the linux environment.  Seems like one of the compiled libraries doesn't like the one generated dll.

**Comment by bonesoul** [comment]
I'm still working on it.

**Comment by mja1175** [comment]
Any chance you'd be interested in helping me with my CoiniumServ?
    On Tuesday, January 23, 2018, 8:42:13 AM MST, Hüseyin Uslu <notifications@github.com> wrote:  
 
 
Closed #11.

**Comment by WildeChild** [comment]
There are two of us actively working on the dev side here, so I think we would be interested in helping collaborate.  We tried out Coinium a few weeks back and enjoyed the project.  Maybe we can move this to another medium to discuss the details?

**Comment by mja1175** [comment]
I would love that. 
What would be the best way to have contact with you?
Text, Email, Phone, Webex?
Let me know, I'm very interested in getting this going ASAP.
Thanks!
    On Tuesday, January 23, 2018, 9:19:48 AM MST, WildeChild <notifications@github.com> wrote:  
 
 
There are two of us actively working on the dev side here, so I think we would be interested in helping collaborate. We tried out Coinium a few weeks back and enjoyed the project. Maybe we can move this to another medium to discuss the details?

**Comment by bonesoul** [comment]
@mja1175 I'm instead working on a complete re-write - this project.

**Comment by mja1175** [comment]
Lets do it!
Whats the best way to get a hold of you guys?
    On Tuesday, January 23, 2018, 11:25:01 AM MST, Hüseyin Uslu <notifications@github.com> wrote:  
 
 
@mja1175 I'm instead working on a complete re-write - this project.

**Comment by rumplin** [comment]
@bonesoul is this project intentionally a one man project?
I see there are other people eager to help, including myself. I'm really interested in seting up a mining pool with this code.

**Comment by bonesoul** [comment]
The project is more then welcome for contributers!

**Comment by mja1175** [comment]
@bonesoul I was wondering if I could get your help in getting my pool running on a new coin. I have everything going without error but rarely have a share accepted and never break anything. Both should be simple. I'm at a loss and could use someones help.

**Comment by bonesoul** [comment]
if it's about coiniumserv, please submit an issue in it's own repo.

**Comment by matrixkloud** [comment]
Hi @bonesoul , I am facing same issue above written. I can't run the application using command dotnet.

**Comment by bonesoul** [comment]
those bınaries are for windows i have not worked them for linıx yet.

**Comment by matrixkloud** [comment]
so how to run your application into linux machine ? I am using ubuntu 16.04.

**Comment by bonesoul** [comment]
not possible yet as development is still ongoing.

**Comment by crptopool** [comment]
I want t thank bonesoul, i really liked the concept of coinium server and i think this is advanced version of the same....I am eager to use it but I am also facing same bug....any advise or fix will be deeply appreciated....

 Copyright (C) 2013 - 2018, hypepool project - Hüseyin Uslu
 https://github.com/bonesoul/hypepool

 hypepool comes with ABSOLUTELY NO WARRANTY.

 You can contribute the development of the project by donating;
 ETH : 0x61aa3e0709e20bcb4aedc2607d4070f1db72e69b

15:58:55 [INF] [-] [Program] hypepool warming-up: v0.0.1
15:58:55 [INF] [-] [Program] running on lin-x64
15:58:55 [INF] [-] [Program] os: Linux 4.14.14-x86_64-linode94 #4 SMP Tue Jan 23 01:06:56 UTC 2018
15:58:55 [INF] [-] [Program] dotnet core: 2.0.5, framework: .NET Core 4.6.0.0
15:58:55 [INF] [-] [Program] running over 4 core system
15:58:55 [INF] [-] [Engine] starting engine..
15:58:55 [INF] [XMR] [MoneroPool] initializing pool..
15:58:55 [FTL] [XMR] [MoneroPool] Unable to load DLL 'libcryptonote': The specified module or one of its dependencies could not be found.
 (Exception from HRESULT: 0x8007007E)
15:58:55 [INF] [XMR] [MoneroJobManager] starting job manager..
15:58:57 [ERR] [XMR] [MoneroJobManager] New job creation failed as daemon responded with [-999] One or more errors occurred. (Object reference not set to an instance of an object.)
15:58:57 [ERR] [-] [Program] caught unhandled exception: Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Hypepool.Monero.MoneroJobManager.<SetupJobUpdates>b__4_1(MoneroJob job) in /home/user/ZNOMP/hypepool/src/Blockchains/Monero/MoneroJobManager.cs:line 73
   at System.Reactive.Linq.ObservableImpl.Do`1._.OnNext(TSource value)
--- End of stack trace from previous location where exception was thrown ---

**Comment by toboho** [comment]
me too.....
